language: cpp
sudo: required
dist: trusty
compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libeigen3-dev

  - git clone https://github.com/gflags/gflags.git gflag
  - cd gflag
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../

  - git clone https://github.com/google/glog.git
  - cd glog
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../

  - git clone https://github.com/google/googletest.git gtest
  - cd gtest
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../

  - tar -jxvf hdf5-1.10.4.tar.bz2
  - cd hdf5-1.10.4/
  - mkdir build && cd build
  - ./../configure
  - make
  - make check
  - make install
  - cd ../../
  
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./example_1
  - ./example_2
  - ./example_3
  - ./example_4