language: cpp
sudo: required
dist: trusty
compiler:
- gcc
# env:
# - EIGEN=3.2.9
# - EIGEN=3.3-beta2

# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - gcc-5
#     - g++-5
# 
# before_install:
# # Set compiler version
# - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

install:
# Install Eigen from source
- sudo apt-get install libeigen3-dev

script:
- mkdir build && cd build
- cmake .. && make
- ./example_1
- ./example_2
