language: cpp
sudo: required
dist: trusty
compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install libeigen3-dev
  - git clone https://github.com/google/glog.git
  - cd glog
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../../

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./example_1
  - ./example_2
  - ./example_3
  - ./example_4